### ISSUE TITLE
Build in ReadTheDocs fails for Sphinx < 2

### ISSUE THREAD

**Issue by Jakob933** [executablebooks/sphinx-tabs#91]
Hi all,

we were using Sphinx-Tabs in ReadTheDocs for an open-source project successfully but since a couple of days (probably after the new release) the build failed with the following logs:

```
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/testfinal11/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/testfinal11/envs/latest/lib/python3.7/site-packages/sphinx_tabs/tabs.py", line 11, in <module>
    from sphinx.highlighting import lexer_classes
ImportError: cannot import name 'lexer_classes' from 'sphinx.highlighting' (/home/docs/checkouts/readthedocs.org/user_builds/testfinal11/envs/latest/lib/python3.7/site-packages/sphinx/highlighting.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/testfinal11/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/testfinal11/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/testfinal11/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/testfinal11/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx_tabs.tabs (exception: cannot import name 'lexer_classes' from 'sphinx.highlighting' (/home/docs/checkouts/readthedocs.org/user_builds/testfinal11/envs/latest/lib/python3.7/site-packages/sphinx/highlighting.py))

Extension error:
Could not import extension sphinx_tabs.tabs (exception: cannot import name 'lexer_classes' from 'sphinx.highlighting' (/home/docs/checkouts/readthedocs.org/user_builds/testfinal11/envs/latest/lib/python3.7/site-packages/sphinx/highlighting.py))
```

After some hours of investigation i found out, that Sphinx >=2 is required and it can be solved by adding `sphinx>=2,<4` to requirements. I know one can recognize this through looking in the codebase but i think it could be mentioned somewhere more obvious (e.g. README) since in the past it worked without specifying Sphinx version.

**Comment by chrisjsewell** [comment]
Somewhere obvious like the change log 😉 https://github.com/executablebooks/sphinx-tabs/blob/master/CHANGELOG.md#v120---2020-08-18

This also a bug of your RTD installation, that sphinx is not automatically updated, given that sphinx>2 is required in the setup.py. I would suggest that there may be an an incompatibility in your dependency tree that is causing this and would anyway start to fail (or be fixed) by the new pip resolver: http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html

**Comment by Jakob933** [comment]
Oh my bad, thanks for the hints!
